sudo: false
language: node_js
node_js:
  # LTS
  - "6"
  - "8"
  - "9"
  - "10"
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm run travis-build
after_success:
  - npm run report-coverage
