sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm run travis-build
after_success:
  - npm run report-coverage
